### PR TITLE
Fix Searchbar filtering

### LINKED ISSUE #161: Searchbar is not filtering properly
It cant find "ActionFeed" and even searching "ui" is inconsistent.

RobloxStudioBeta_BJf3Hs1vn7

### PR DESCRIPTION
**Pull request by hy2k**
# Problem

The current implementation of the filtering functionality in our Storybook tree view has a limitation. It only checks if the name of the current component node matches the filter text. This means that even if a story matches the filter, if any of its parent folders does not match the filter, the entire subtree gets skipped during rendering.

# Solution

The proposed solution modifies this behavior for non-story nodes (e.g., storybooks, folders). Now, instead of checking if the node's name matches the filter, we check if the node has at least one descendant story that matches the filter. This ensures that folders containing matching stories are not erroneously hidden due to the folder name not matching the filter.

For story nodes, the behavior remains the same as before: the story is displayed if its name matches the filter.

Fix #161 

# Checklist

- [ ] Ran `./bin/test.sh` locally before merging

### CODE REVIEW

File: src/Modules/getTreeDescendants.lua [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+local function getTreeDescendants(root: types.ComponentTreeNode): { types.ComponentTreeNode }
+	local descendants: { types.ComponentTreeNode } = {}
+
+	local function traverse(node: types.ComponentTreeNode, isRoot: boolean)
+		if not isRoot then
+			table.insert(descendants, node)
+		end
+
+		for _, child in ipairs(node.children) do
```
Comment (vocksel) [inline src/Modules/getTreeDescendants.lua:13]: Luau knows how to handle tables without `pairs` and `ipairs` now. This can be simplified 
```suggestion
		for _, child in node.children do
```

File: src/Components/ComponentTree/Component/init.lua [hunk 2]
```diff
@@ -57,10 +58,20 @@ local function Component(props: Props)
...
 
-	if props.filter and props.node.icon ~= "storybook" then
-		local match = props.node.name:lower():match(props.filter:lower())
+	if props.filter then
+		if props.node.icon == "story" and not props.node.name:lower():match(props.filter:lower()) then
+			return
+		end
+
+		local isEmpty = true
+		for _, descendant in ipairs(getTreeDescendants(props.node)) do
```
Comment (vocksel) [inline src/Components/ComponentTree/Component/init.lua:67]: Can drop `ipairs` here too

**Review by vocksel — COMMENTED** [review]
Thanks for the PR! And for the unit tests :) Couple comments but otherwise looks great

File: src/Modules/getTreeDescendants.lua (hunk 1 above)
Comment (hy2k) [reply src/Modules/getTreeDescendants.lua]: Thanks for your suggestion. Just applied the changes.

**Review by vocksel — APPROVED** [review]
Approved! Feel free to merge
